from __future__ import annotations

from enum import Enum


class RepositoryAgentPhase(str, Enum):
    INTAKE = "INTAKE"
    ANSWERING_QUESTION = "ANSWERING_QUESTION"
    PLANNING = "PLANNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    BRANCH_PERMISSION = "BRANCH_PERMISSION"
    BRANCH_NAME = "BRANCH_NAME"
    BRANCH_CONFIRMATION = "BRANCH_CONFIRMATION"
    PLAN_STEP_REVIEW = "PLAN_STEP_REVIEW"
    WAITING_EXECUTION_APPROVAL = "WAITING_EXECUTION_APPROVAL"
    EXECUTING = "EXECUTING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    FINALIZING = "FINALIZING"
    DONE = "DONE"
    FAILED = "FAILED"


class TaskAgentStatus(str, Enum):
    CREATED = "CREATED"
    INSPECTING = "INSPECTING"
    WORKING = "WORKING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    VALIDATING = "VALIDATING"
    DONE = "DONE"
    FAILED = "FAILED"
    DEAD = "DEAD"

